"""...

Revision ID: 00ab68b13fa7
Revises: 
Create Date: 2026-09-08 12:53:03.740846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '00ab68b13fa7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('market_planner',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS "market_planner"')
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meta_description', sa.String(length=255), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=False),
    sa.Column('sections', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('call_to_action', sa.Text(), nullable=False),
    sa.Column('theme_index', sa.Integer(), nullable=True),
    sa.Column('scheduled_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('month_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_blog_posts_company_id'), 'blog_posts', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_blog_posts_id'), 'blog_posts', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_blog_posts_uuid'), 'blog_posts', ['uuid'], unique=True, schema='market_planner')
    op.create_table('channel_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('blog_post_active', sa.Boolean(), nullable=False),
    sa.Column('blog_post_count', sa.Integer(), nullable=False),
    sa.Column('email_campaign_active', sa.Boolean(), nullable=False),
    sa.Column('email_campaign_count', sa.Integer(), nullable=False),
    sa.Column('facebook_active', sa.Boolean(), nullable=False),
    sa.Column('facebook_post_count', sa.Integer(), nullable=False),
    sa.Column('instagram_active', sa.Boolean(), nullable=False),
    sa.Column('instagram_post_count', sa.Integer(), nullable=False),
    sa.Column('linkedin_active', sa.Boolean(), nullable=False),
    sa.Column('linkedin_post_count', sa.Integer(), nullable=False),
    sa.Column('tiktok_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_channel_config_company_id'), 'channel_config', ['company_id'], unique=True, schema='market_planner')
    op.create_index(op.f('ix_market_planner_channel_config_id'), 'channel_config', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_channel_config_uuid'), 'channel_config', ['uuid'], unique=True, schema='market_planner')
    op.create_table('facebook_insta_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fb_user_id', sa.String(length=255), nullable=True),
    sa.Column('user_long_token', sa.Text(), nullable=True),
    sa.Column('flow_type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_facebook_insta_accounts_company_id'), 'facebook_insta_accounts', ['company_id'], unique=True, schema='market_planner')
    op.create_index(op.f('ix_market_planner_facebook_insta_accounts_id'), 'facebook_insta_accounts', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_facebook_insta_accounts_uuid'), 'facebook_insta_accounts', ['uuid'], unique=True, schema='market_planner')
    op.create_table('image_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_image_config_company_id'), 'image_config', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_image_config_id'), 'image_config', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_image_config_uuid'), 'image_config', ['uuid'], unique=True, schema='market_planner')
    op.create_table('linkedin_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=255), nullable=False),
    sa.Column('linkedin_id', sa.Text(), nullable=True),
    sa.Column('author_urn', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_linkedin_accounts_company_id'), 'linkedin_accounts', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_linkedin_accounts_id'), 'linkedin_accounts', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_linkedin_accounts_uuid'), 'linkedin_accounts', ['uuid'], unique=True, schema='market_planner')
    op.create_table('newsletter_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('subject_line', sa.String(length=255), nullable=True),
    sa.Column('preheader', sa.String(length=255), nullable=True),
    sa.Column('greeting', sa.String(length=255), nullable=True),
    sa.Column('opening_paragraph', sa.Text(), nullable=True),
    sa.Column('main_content', sa.Text(), nullable=True),
    sa.Column('practical_tips_section', sa.Text(), nullable=True),
    sa.Column('call_to_action', sa.Text(), nullable=True),
    sa.Column('closing', sa.Text(), nullable=True),
    sa.Column('theme_index', sa.Integer(), nullable=True),
    sa.Column('scheduled_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('month_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_newsletter_posts_company_id'), 'newsletter_posts', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_newsletter_posts_id'), 'newsletter_posts', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_newsletter_posts_uuid'), 'newsletter_posts', ['uuid'], unique=True, schema='market_planner')
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('overlay_text', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('month_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_month', sa.Integer(), nullable=True),
    sa.Column('scheduled_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('theme_index', sa.Integer(), nullable=True),
    sa.Column('variation_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_posts_company_id'), 'posts', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_posts_id'), 'posts', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_posts_uuid'), 'posts', ['uuid'], unique=True, schema='market_planner')
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_product_categories_company_id'), 'product_categories', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_product_categories_id'), 'product_categories', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_product_categories_name'), 'product_categories', ['name'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_product_categories_uuid'), 'product_categories', ['uuid'], unique=True, schema='market_planner')
    op.create_table('telegram_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_telegram_chats_company_id'), 'telegram_chats', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_telegram_chats_id'), 'telegram_chats', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_telegram_chats_telegram_chat_id'), 'telegram_chats', ['telegram_chat_id'], unique=True, schema='market_planner')
    op.create_index(op.f('ix_market_planner_telegram_chats_user_id'), 'telegram_chats', ['user_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_telegram_chats_uuid'), 'telegram_chats', ['uuid'], unique=True, schema='market_planner')
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('month_id', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_themes_company_id'), 'themes', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_themes_id'), 'themes', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_themes_uuid'), 'themes', ['uuid'], unique=True, schema='market_planner')
    op.create_table('tiktok_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('open_id', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=255), nullable=True),
    sa.Column('access_expires_in', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('refresh_expires_in', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_tiktok_accounts_company_id'), 'tiktok_accounts', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_tiktok_accounts_id'), 'tiktok_accounts', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_tiktok_accounts_uuid'), 'tiktok_accounts', ['uuid'], unique=True, schema='market_planner')
    op.create_table('whatsapp_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_whatsapp_accounts_company_id'), 'whatsapp_accounts', ['company_id'], unique=True, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_accounts_id'), 'whatsapp_accounts', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_accounts_phone_number'), 'whatsapp_accounts', ['phone_number'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_accounts_uuid'), 'whatsapp_accounts', ['uuid'], unique=True, schema='market_planner')
    op.create_table('facebook_insta_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('facebook_insta_account_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=255), nullable=True),
    sa.Column('page_name', sa.String(length=255), nullable=True),
    sa.Column('page_access_token', sa.Text(), nullable=True),
    sa.Column('page_profile_picture_url', sa.Text(), nullable=True),
    sa.Column('instagram_connected', sa.Boolean(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['facebook_insta_account_id'], ['market_planner.facebook_insta_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_facebook_insta_pages_facebook_insta_account_id'), 'facebook_insta_pages', ['facebook_insta_account_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_facebook_insta_pages_id'), 'facebook_insta_pages', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_facebook_insta_pages_page_id'), 'facebook_insta_pages', ['page_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_facebook_insta_pages_uuid'), 'facebook_insta_pages', ['uuid'], unique=True, schema='market_planner')
    op.create_table('linkedin_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('linkedin_account_id', sa.Integer(), nullable=True),
    sa.Column('linkedin_id', sa.String(length=255), nullable=True),
    sa.Column('author_urn', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['linkedin_account_id'], ['market_planner.linkedin_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_linkedin_pages_id'), 'linkedin_pages', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_linkedin_pages_uuid'), 'linkedin_pages', ['uuid'], unique=True, schema='market_planner')
    op.create_table('linkedin_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('linkedin_account_id', sa.Integer(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('media_urls', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('target_urn', sa.String(length=255), nullable=False),
    sa.Column('linkedin_share_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linkedin_account_id'], ['market_planner.linkedin_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_linkedin_posts_company_id'), 'linkedin_posts', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_linkedin_posts_id'), 'linkedin_posts', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_linkedin_posts_uuid'), 'linkedin_posts', ['uuid'], unique=True, schema='market_planner')
    op.create_table('scraped_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('is_product', sa.Boolean(), nullable=True),
    sa.Column('features', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['market_planner.product_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_scraped_products_category'), 'scraped_products', ['category'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_scraped_products_category_id'), 'scraped_products', ['category_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_scraped_products_company_id'), 'scraped_products', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_scraped_products_id'), 'scraped_products', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_scraped_products_source_url'), 'scraped_products', ['source_url'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_scraped_products_uuid'), 'scraped_products', ['uuid'], unique=True, schema='market_planner')
    op.create_table('telegram_pending_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['market_planner.telegram_chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_telegram_pending_approvals_chat_id'), 'telegram_pending_approvals', ['chat_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_telegram_pending_approvals_company_id'), 'telegram_pending_approvals', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_telegram_pending_approvals_id'), 'telegram_pending_approvals', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_telegram_pending_approvals_uuid'), 'telegram_pending_approvals', ['uuid'], unique=True, schema='market_planner')
    op.create_table('telegram_theme_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.String(length=255), nullable=True),
    sa.Column('selected_theme', sa.Integer(), nullable=True),
    sa.Column('selected_theme_title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['market_planner.telegram_chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_telegram_theme_selections_chat_id'), 'telegram_theme_selections', ['chat_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_telegram_theme_selections_company_id'), 'telegram_theme_selections', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_telegram_theme_selections_id'), 'telegram_theme_selections', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_telegram_theme_selections_status'), 'telegram_theme_selections', ['status'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_telegram_theme_selections_uuid'), 'telegram_theme_selections', ['uuid'], unique=True, schema='market_planner')
    op.create_table('tiktok_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tiktok_account_id', sa.Integer(), nullable=False),
    sa.Column('publish_id', sa.Text(), nullable=True),
    sa.Column('upload_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tiktok_account_id'], ['market_planner.tiktok_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_tiktok_posts_company_id'), 'tiktok_posts', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_tiktok_posts_id'), 'tiktok_posts', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_tiktok_posts_tiktok_account_id'), 'tiktok_posts', ['tiktok_account_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_tiktok_posts_uuid'), 'tiktok_posts', ['uuid'], unique=True, schema='market_planner')
    op.create_table('whatsapp_post_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('recipient_phone', sa.String(length=32), nullable=True),
    sa.Column('message_token', sa.String(length=64), nullable=True),
    sa.Column('twilio_message_sid', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='sent', nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['market_planner.posts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_whatsapp_post_deliveries_company_id'), 'whatsapp_post_deliveries', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_post_deliveries_id'), 'whatsapp_post_deliveries', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_post_deliveries_message_token'), 'whatsapp_post_deliveries', ['message_token'], unique=True, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_post_deliveries_post_id'), 'whatsapp_post_deliveries', ['post_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_post_deliveries_recipient_phone'), 'whatsapp_post_deliveries', ['recipient_phone'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_post_deliveries_status'), 'whatsapp_post_deliveries', ['status'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_post_deliveries_twilio_message_sid'), 'whatsapp_post_deliveries', ['twilio_message_sid'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_post_deliveries_uuid'), 'whatsapp_post_deliveries', ['uuid'], unique=True, schema='market_planner')
    op.create_table('whatsapp_theme_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('recipient_phone', sa.String(length=32), nullable=True),
    sa.Column('message_token', sa.String(length=64), nullable=True),
    sa.Column('twilio_message_sid', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('month', sa.String(length=32), nullable=True),
    sa.Column('option1_title', sa.String(length=255), nullable=True),
    sa.Column('option1_desc', sa.Text(), nullable=True),
    sa.Column('option2_title', sa.String(length=255), nullable=True),
    sa.Column('option2_desc', sa.Text(), nullable=True),
    sa.Column('selected_option', sa.String(length=10), nullable=True),
    sa.Column('selected_option_title', sa.String(length=255), nullable=True),
    sa.Column('selected_option_desc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['market_planner.themes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_whatsapp_theme_deliveries_company_id'), 'whatsapp_theme_deliveries', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_theme_deliveries_id'), 'whatsapp_theme_deliveries', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_theme_deliveries_message_token'), 'whatsapp_theme_deliveries', ['message_token'], unique=True, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_theme_deliveries_recipient_phone'), 'whatsapp_theme_deliveries', ['recipient_phone'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_theme_deliveries_status'), 'whatsapp_theme_deliveries', ['status'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_theme_deliveries_theme_id'), 'whatsapp_theme_deliveries', ['theme_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_theme_deliveries_twilio_message_sid'), 'whatsapp_theme_deliveries', ['twilio_message_sid'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_whatsapp_theme_deliveries_uuid'), 'whatsapp_theme_deliveries', ['uuid'], unique=True, schema='market_planner')
    op.create_table('instagram_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ig_user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=255), nullable=False),
    sa.Column('media_count', sa.Integer(), nullable=False),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('facebook_insta_page_id', sa.Integer(), nullable=True),
    sa.Column('facebook_page_name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=255), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facebook_insta_page_id'], ['market_planner.facebook_insta_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_instagram_accounts_company_id'), 'instagram_accounts', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_instagram_accounts_id'), 'instagram_accounts', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_instagram_accounts_uuid'), 'instagram_accounts', ['uuid'], unique=True, schema='market_planner')
    op.create_table('facebook_insta_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('facebook_insta_account_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('facebook_page_id', sa.Integer(), nullable=True),
    sa.Column('instagram_account_id', sa.Integer(), nullable=True),
    sa.Column('platform_post_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('platform_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facebook_insta_account_id'], ['market_planner.facebook_insta_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facebook_page_id'], ['market_planner.facebook_insta_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['market_planner.instagram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_facebook_insta_posts_company_id'), 'facebook_insta_posts', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_facebook_insta_posts_facebook_insta_account_id'), 'facebook_insta_posts', ['facebook_insta_account_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_facebook_insta_posts_facebook_page_id'), 'facebook_insta_posts', ['facebook_page_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_facebook_insta_posts_id'), 'facebook_insta_posts', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_facebook_insta_posts_instagram_account_id'), 'facebook_insta_posts', ['instagram_account_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_facebook_insta_posts_platform_post_id'), 'facebook_insta_posts', ['platform_post_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_facebook_insta_posts_uuid'), 'facebook_insta_posts', ['uuid'], unique=True, schema='market_planner')
    op.create_table('instagram_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('media_id', sa.Text(), nullable=True),
    sa.Column('platform_post_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('platform_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['market_planner.instagram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='market_planner'
    )
    op.create_index(op.f('ix_market_planner_instagram_posts_company_id'), 'instagram_posts', ['company_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_instagram_posts_id'), 'instagram_posts', ['id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_instagram_posts_instagram_account_id'), 'instagram_posts', ['instagram_account_id'], unique=False, schema='market_planner')
    op.create_index(op.f('ix_market_planner_instagram_posts_uuid'), 'instagram_posts', ['uuid'], unique=True, schema='market_planner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_planner_instagram_posts_uuid'), table_name='instagram_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_instagram_posts_instagram_account_id'), table_name='instagram_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_instagram_posts_id'), table_name='instagram_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_instagram_posts_company_id'), table_name='instagram_posts', schema='market_planner')
    op.drop_table('instagram_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_facebook_insta_posts_uuid'), table_name='facebook_insta_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_facebook_insta_posts_platform_post_id'), table_name='facebook_insta_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_facebook_insta_posts_instagram_account_id'), table_name='facebook_insta_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_facebook_insta_posts_id'), table_name='facebook_insta_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_facebook_insta_posts_facebook_page_id'), table_name='facebook_insta_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_facebook_insta_posts_facebook_insta_account_id'), table_name='facebook_insta_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_facebook_insta_posts_company_id'), table_name='facebook_insta_posts', schema='market_planner')
    op.drop_table('facebook_insta_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_instagram_accounts_uuid'), table_name='instagram_accounts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_instagram_accounts_id'), table_name='instagram_accounts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_instagram_accounts_company_id'), table_name='instagram_accounts', schema='market_planner')
    op.drop_table('instagram_accounts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_theme_deliveries_uuid'), table_name='whatsapp_theme_deliveries', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_theme_deliveries_twilio_message_sid'), table_name='whatsapp_theme_deliveries', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_theme_deliveries_theme_id'), table_name='whatsapp_theme_deliveries', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_theme_deliveries_status'), table_name='whatsapp_theme_deliveries', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_theme_deliveries_recipient_phone'), table_name='whatsapp_theme_deliveries', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_theme_deliveries_message_token'), table_name='whatsapp_theme_deliveries', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_theme_deliveries_id'), table_name='whatsapp_theme_deliveries', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_theme_deliveries_company_id'), table_name='whatsapp_theme_deliveries', schema='market_planner')
    op.drop_table('whatsapp_theme_deliveries', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_post_deliveries_uuid'), table_name='whatsapp_post_deliveries', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_post_deliveries_twilio_message_sid'), table_name='whatsapp_post_deliveries', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_post_deliveries_status'), table_name='whatsapp_post_deliveries', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_post_deliveries_recipient_phone'), table_name='whatsapp_post_deliveries', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_post_deliveries_post_id'), table_name='whatsapp_post_deliveries', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_post_deliveries_message_token'), table_name='whatsapp_post_deliveries', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_post_deliveries_id'), table_name='whatsapp_post_deliveries', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_post_deliveries_company_id'), table_name='whatsapp_post_deliveries', schema='market_planner')
    op.drop_table('whatsapp_post_deliveries', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_tiktok_posts_uuid'), table_name='tiktok_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_tiktok_posts_tiktok_account_id'), table_name='tiktok_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_tiktok_posts_id'), table_name='tiktok_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_tiktok_posts_company_id'), table_name='tiktok_posts', schema='market_planner')
    op.drop_table('tiktok_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_telegram_theme_selections_uuid'), table_name='telegram_theme_selections', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_telegram_theme_selections_status'), table_name='telegram_theme_selections', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_telegram_theme_selections_id'), table_name='telegram_theme_selections', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_telegram_theme_selections_company_id'), table_name='telegram_theme_selections', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_telegram_theme_selections_chat_id'), table_name='telegram_theme_selections', schema='market_planner')
    op.drop_table('telegram_theme_selections', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_telegram_pending_approvals_uuid'), table_name='telegram_pending_approvals', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_telegram_pending_approvals_id'), table_name='telegram_pending_approvals', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_telegram_pending_approvals_company_id'), table_name='telegram_pending_approvals', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_telegram_pending_approvals_chat_id'), table_name='telegram_pending_approvals', schema='market_planner')
    op.drop_table('telegram_pending_approvals', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_scraped_products_uuid'), table_name='scraped_products', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_scraped_products_source_url'), table_name='scraped_products', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_scraped_products_id'), table_name='scraped_products', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_scraped_products_company_id'), table_name='scraped_products', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_scraped_products_category_id'), table_name='scraped_products', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_scraped_products_category'), table_name='scraped_products', schema='market_planner')
    op.drop_table('scraped_products', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_linkedin_posts_uuid'), table_name='linkedin_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_linkedin_posts_id'), table_name='linkedin_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_linkedin_posts_company_id'), table_name='linkedin_posts', schema='market_planner')
    op.drop_table('linkedin_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_linkedin_pages_uuid'), table_name='linkedin_pages', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_linkedin_pages_id'), table_name='linkedin_pages', schema='market_planner')
    op.drop_table('linkedin_pages', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_facebook_insta_pages_uuid'), table_name='facebook_insta_pages', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_facebook_insta_pages_page_id'), table_name='facebook_insta_pages', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_facebook_insta_pages_id'), table_name='facebook_insta_pages', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_facebook_insta_pages_facebook_insta_account_id'), table_name='facebook_insta_pages', schema='market_planner')
    op.drop_table('facebook_insta_pages', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_accounts_uuid'), table_name='whatsapp_accounts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_accounts_phone_number'), table_name='whatsapp_accounts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_accounts_id'), table_name='whatsapp_accounts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_whatsapp_accounts_company_id'), table_name='whatsapp_accounts', schema='market_planner')
    op.drop_table('whatsapp_accounts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_tiktok_accounts_uuid'), table_name='tiktok_accounts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_tiktok_accounts_id'), table_name='tiktok_accounts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_tiktok_accounts_company_id'), table_name='tiktok_accounts', schema='market_planner')
    op.drop_table('tiktok_accounts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_themes_uuid'), table_name='themes', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_themes_id'), table_name='themes', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_themes_company_id'), table_name='themes', schema='market_planner')
    op.drop_table('themes', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_telegram_chats_uuid'), table_name='telegram_chats', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_telegram_chats_user_id'), table_name='telegram_chats', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_telegram_chats_telegram_chat_id'), table_name='telegram_chats', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_telegram_chats_id'), table_name='telegram_chats', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_telegram_chats_company_id'), table_name='telegram_chats', schema='market_planner')
    op.drop_table('telegram_chats', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_product_categories_uuid'), table_name='product_categories', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_product_categories_name'), table_name='product_categories', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_product_categories_id'), table_name='product_categories', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_product_categories_company_id'), table_name='product_categories', schema='market_planner')
    op.drop_table('product_categories', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_posts_uuid'), table_name='posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_posts_id'), table_name='posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_posts_company_id'), table_name='posts', schema='market_planner')
    op.drop_table('posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_newsletter_posts_uuid'), table_name='newsletter_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_newsletter_posts_id'), table_name='newsletter_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_newsletter_posts_company_id'), table_name='newsletter_posts', schema='market_planner')
    op.drop_table('newsletter_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_linkedin_accounts_uuid'), table_name='linkedin_accounts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_linkedin_accounts_id'), table_name='linkedin_accounts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_linkedin_accounts_company_id'), table_name='linkedin_accounts', schema='market_planner')
    op.drop_table('linkedin_accounts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_image_config_uuid'), table_name='image_config', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_image_config_id'), table_name='image_config', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_image_config_company_id'), table_name='image_config', schema='market_planner')
    op.drop_table('image_config', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_facebook_insta_accounts_uuid'), table_name='facebook_insta_accounts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_facebook_insta_accounts_id'), table_name='facebook_insta_accounts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_facebook_insta_accounts_company_id'), table_name='facebook_insta_accounts', schema='market_planner')
    op.drop_table('facebook_insta_accounts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_channel_config_uuid'), table_name='channel_config', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_channel_config_id'), table_name='channel_config', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_channel_config_company_id'), table_name='channel_config', schema='market_planner')
    op.drop_table('channel_config', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_blog_posts_uuid'), table_name='blog_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_blog_posts_id'), table_name='blog_posts', schema='market_planner')
    op.drop_index(op.f('ix_market_planner_blog_posts_company_id'), table_name='blog_posts', schema='market_planner')
    op.drop_table('blog_posts', schema='market_planner')
    op.execute('DROP SCHEMA IF EXISTS "market_planner" CASCADE')
    # ### end Alembic commands ###
