"""...

Revision ID: b7cff179c82e
Revises: 
Create Date: 2026-09-08 12:52:43.291881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b7cff179c82e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('core',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS "core"')
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('company_info', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('target_group', sa.Text(), nullable=True),
    sa.Column('tone_analysis', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('theme_colors', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('products', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('fonts_typography', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('matched_fonts', sa.JSON(), nullable=True),
    sa.Column('product_categories', sa.JSON(), nullable=True),
    sa.Column('tier', sa.String(length=10), server_default=sa.text("'FREE'"), nullable=True),
    sa.Column('agent_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_companies_company_name'), 'companies', ['company_name'], unique=False, schema='core')
    op.create_index(op.f('ix_core_companies_id'), 'companies', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_companies_uuid'), 'companies', ['uuid'], unique=True, schema='core')
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_features_id'), 'features', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_features_name'), 'features', ['name'], unique=False, schema='core')
    op.create_index(op.f('ix_core_features_uuid'), 'features', ['uuid'], unique=True, schema='core')
    op.create_table('installed_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('installed_version', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('install_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('schema_name', sa.String(length=63), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_installed_products_id'), 'installed_products', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_installed_products_product_name'), 'installed_products', ['product_name'], unique=True, schema='core')
    op.create_index(op.f('ix_core_installed_products_uuid'), 'installed_products', ['uuid'], unique=True, schema='core')
    op.create_table('log_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='core'
    )
    op.create_index(op.f('ix_core_log_records_company_id'), 'log_records', ['company_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_log_records_timestamp'), 'log_records', ['timestamp'], unique=False, schema='core')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_roles_id'), 'roles', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_roles_name'), 'roles', ['name'], unique=True, schema='core')
    op.create_index(op.f('ix_core_roles_uuid'), 'roles', ['uuid'], unique=True, schema='core')
    op.create_table('tool_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_tool_execution_logs_company_id'), 'tool_execution_logs', ['company_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_tool_execution_logs_timestamp'), 'tool_execution_logs', ['timestamp'], unique=False, schema='core')
    op.create_index(op.f('ix_core_tool_execution_logs_tool_name'), 'tool_execution_logs', ['tool_name'], unique=False, schema='core')
    op.create_index(op.f('ix_core_tool_execution_logs_uuid'), 'tool_execution_logs', ['uuid'], unique=True, schema='core')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_fully_approved', sa.Boolean(), nullable=False),
    sa.Column('has_created_company', sa.Boolean(), nullable=False),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_users_email'), 'users', ['email'], unique=True, schema='core')
    op.create_index(op.f('ix_core_users_firebase_uid'), 'users', ['firebase_uid'], unique=True, schema='core')
    op.create_index(op.f('ix_core_users_id'), 'users', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_users_uuid'), 'users', ['uuid'], unique=True, schema='core')
    op.create_table('company_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('supported_languages', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('default_language', sa.String(), nullable=False),
    sa.Column('location_mode', sa.String(), nullable=False),
    sa.Column('company_address', sa.String(), nullable=True),
    sa.Column('business_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exception_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_email_recipients', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('bookings_enabled', sa.Boolean(), nullable=False),
    sa.Column('caller_data_collection', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('callback_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('phone_summary', sa.Boolean(), nullable=True),
    sa.Column('email_summary', sa.Boolean(), nullable=True),
    sa.Column('daily_summary', sa.Boolean(), nullable=True),
    sa.Column('customer_sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_email', sa.String(length=255), nullable=True),
    sa.Column('scheduled_email_time', sa.Time(timezone=True), nullable=True),
    sa.Column('scheduled_timezone', sa.String(length=128), nullable=True),
    sa.Column('usage_warning_sent_month', sa.String(length=7), nullable=True),
    sa.Column('usage_warning_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_company_configs_company_id'), 'company_configs', ['company_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_company_configs_id'), 'company_configs', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_company_configs_uuid'), 'company_configs', ['uuid'], unique=True, schema='core')
    op.create_table('company_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_id'], ['core.features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_company_features_company_id'), 'company_features', ['company_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_company_features_feature_id'), 'company_features', ['feature_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_company_features_id'), 'company_features', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_company_features_uuid'), 'company_features', ['uuid'], unique=True, schema='core')
    op.create_table('company_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['core.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_company'),
    schema='core'
    )
    op.create_index(op.f('ix_core_company_users_id'), 'company_users', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_company_users_uuid'), 'company_users', ['uuid'], unique=True, schema='core')
    op.create_table('image_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('composition_and_style', sa.Text(), nullable=True),
    sa.Column('environment_settings', sa.Text(), nullable=True),
    sa.Column('image_types_and_animation', sa.Text(), nullable=True),
    sa.Column('keywords_for_ai_image_generation', sa.Text(), nullable=True),
    sa.Column('lighting_and_color_tone', sa.Text(), nullable=True),
    sa.Column('subjects_and_people', sa.Text(), nullable=True),
    sa.Column('technology_elements', sa.Text(), nullable=True),
    sa.Column('theme_and_atmosphere', sa.Text(), nullable=True),
    sa.Column('analyzed_images_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('image_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_image_analysis_company_id'), 'image_analysis', ['company_id'], unique=True, schema='core')
    op.create_index(op.f('ix_core_image_analysis_id'), 'image_analysis', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_image_analysis_uuid'), 'image_analysis', ['uuid'], unique=True, schema='core')
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=True),
    sa.Column('accepted_by_id', sa.Integer(), nullable=True),
    sa.Column('email_status', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['core.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_invitations_accepted_by_id'), 'invitations', ['accepted_by_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_invitations_company_id'), 'invitations', ['company_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_invitations_email'), 'invitations', ['email'], unique=False, schema='core')
    op.create_index(op.f('ix_core_invitations_id'), 'invitations', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_invitations_inviter_id'), 'invitations', ['inviter_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_invitations_status'), 'invitations', ['status'], unique=False, schema='core')
    op.create_index(op.f('ix_core_invitations_token'), 'invitations', ['token'], unique=True, schema='core')
    op.create_index(op.f('ix_core_invitations_uuid'), 'invitations', ['uuid'], unique=True, schema='core')
    op.create_table('usage_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_usage_metrics_action'), 'usage_metrics', ['action'], unique=False, schema='core')
    op.create_index(op.f('ix_core_usage_metrics_channel'), 'usage_metrics', ['channel'], unique=False, schema='core')
    op.create_index(op.f('ix_core_usage_metrics_company_id'), 'usage_metrics', ['company_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_usage_metrics_date'), 'usage_metrics', ['date'], unique=False, schema='core')
    op.create_index(op.f('ix_core_usage_metrics_feature'), 'usage_metrics', ['feature'], unique=False, schema='core')
    op.create_index(op.f('ix_core_usage_metrics_user_id'), 'usage_metrics', ['user_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_usage_metrics_user_id'), table_name='usage_metrics', schema='core')
    op.drop_index(op.f('ix_core_usage_metrics_feature'), table_name='usage_metrics', schema='core')
    op.drop_index(op.f('ix_core_usage_metrics_date'), table_name='usage_metrics', schema='core')
    op.drop_index(op.f('ix_core_usage_metrics_company_id'), table_name='usage_metrics', schema='core')
    op.drop_index(op.f('ix_core_usage_metrics_channel'), table_name='usage_metrics', schema='core')
    op.drop_index(op.f('ix_core_usage_metrics_action'), table_name='usage_metrics', schema='core')
    op.drop_table('usage_metrics', schema='core')
    op.drop_index(op.f('ix_core_invitations_uuid'), table_name='invitations', schema='core')
    op.drop_index(op.f('ix_core_invitations_token'), table_name='invitations', schema='core')
    op.drop_index(op.f('ix_core_invitations_status'), table_name='invitations', schema='core')
    op.drop_index(op.f('ix_core_invitations_inviter_id'), table_name='invitations', schema='core')
    op.drop_index(op.f('ix_core_invitations_id'), table_name='invitations', schema='core')
    op.drop_index(op.f('ix_core_invitations_email'), table_name='invitations', schema='core')
    op.drop_index(op.f('ix_core_invitations_company_id'), table_name='invitations', schema='core')
    op.drop_index(op.f('ix_core_invitations_accepted_by_id'), table_name='invitations', schema='core')
    op.drop_table('invitations', schema='core')
    op.drop_index(op.f('ix_core_image_analysis_uuid'), table_name='image_analysis', schema='core')
    op.drop_index(op.f('ix_core_image_analysis_id'), table_name='image_analysis', schema='core')
    op.drop_index(op.f('ix_core_image_analysis_company_id'), table_name='image_analysis', schema='core')
    op.drop_table('image_analysis', schema='core')
    op.drop_index(op.f('ix_core_company_users_uuid'), table_name='company_users', schema='core')
    op.drop_index(op.f('ix_core_company_users_id'), table_name='company_users', schema='core')
    op.drop_table('company_users', schema='core')
    op.drop_index(op.f('ix_core_company_features_uuid'), table_name='company_features', schema='core')
    op.drop_index(op.f('ix_core_company_features_id'), table_name='company_features', schema='core')
    op.drop_index(op.f('ix_core_company_features_feature_id'), table_name='company_features', schema='core')
    op.drop_index(op.f('ix_core_company_features_company_id'), table_name='company_features', schema='core')
    op.drop_table('company_features', schema='core')
    op.drop_index(op.f('ix_core_company_configs_uuid'), table_name='company_configs', schema='core')
    op.drop_index(op.f('ix_core_company_configs_id'), table_name='company_configs', schema='core')
    op.drop_index(op.f('ix_core_company_configs_company_id'), table_name='company_configs', schema='core')
    op.drop_table('company_configs', schema='core')
    op.drop_index(op.f('ix_core_users_uuid'), table_name='users', schema='core')
    op.drop_index(op.f('ix_core_users_id'), table_name='users', schema='core')
    op.drop_index(op.f('ix_core_users_firebase_uid'), table_name='users', schema='core')
    op.drop_index(op.f('ix_core_users_email'), table_name='users', schema='core')
    op.drop_table('users', schema='core')
    op.drop_index(op.f('ix_core_tool_execution_logs_uuid'), table_name='tool_execution_logs', schema='core')
    op.drop_index(op.f('ix_core_tool_execution_logs_tool_name'), table_name='tool_execution_logs', schema='core')
    op.drop_index(op.f('ix_core_tool_execution_logs_timestamp'), table_name='tool_execution_logs', schema='core')
    op.drop_index(op.f('ix_core_tool_execution_logs_company_id'), table_name='tool_execution_logs', schema='core')
    op.drop_table('tool_execution_logs', schema='core')
    op.drop_index(op.f('ix_core_roles_uuid'), table_name='roles', schema='core')
    op.drop_index(op.f('ix_core_roles_name'), table_name='roles', schema='core')
    op.drop_index(op.f('ix_core_roles_id'), table_name='roles', schema='core')
    op.drop_table('roles', schema='core')
    op.drop_index(op.f('ix_core_log_records_timestamp'), table_name='log_records', schema='core')
    op.drop_index(op.f('ix_core_log_records_company_id'), table_name='log_records', schema='core')
    op.drop_table('log_records', schema='core')
    op.drop_index(op.f('ix_core_installed_products_uuid'), table_name='installed_products', schema='core')
    op.drop_index(op.f('ix_core_installed_products_product_name'), table_name='installed_products', schema='core')
    op.drop_index(op.f('ix_core_installed_products_id'), table_name='installed_products', schema='core')
    op.drop_table('installed_products', schema='core')
    op.drop_index(op.f('ix_core_features_uuid'), table_name='features', schema='core')
    op.drop_index(op.f('ix_core_features_name'), table_name='features', schema='core')
    op.drop_index(op.f('ix_core_features_id'), table_name='features', schema='core')
    op.drop_table('features', schema='core')
    op.drop_index(op.f('ix_core_companies_uuid'), table_name='companies', schema='core')
    op.drop_index(op.f('ix_core_companies_id'), table_name='companies', schema='core')
    op.drop_index(op.f('ix_core_companies_company_name'), table_name='companies', schema='core')
    op.drop_table('companies', schema='core')
    op.execute('DROP SCHEMA IF EXISTS "core" CASCADE')
    # ### end Alembic commands ###
