"""...

Revision ID: ea18a34f16ac
Revises: 
Create Date: 2026-09-08 12:53:20.495023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

revision: str = 'ea18a34f16ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('knowledge',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS "knowledge"')
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('chat_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('greeting_message', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('lead_collection_enabled', sa.Boolean(), nullable=True),
    sa.Column('lead_recipient_email', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['core.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_knowledge_chat_bots_company_id'), 'chat_bots', ['company_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_chat_bots_created_by_id'), 'chat_bots', ['created_by_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_chat_bots_id'), 'chat_bots', ['id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_chat_bots_uuid'), 'chat_bots', ['uuid'], unique=True, schema='knowledge')
    op.create_table('company_faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('question_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_knowledge_company_faqs_company_id'), 'company_faqs', ['company_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_company_faqs_id'), 'company_faqs', ['id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_company_faqs_question_id'), 'company_faqs', ['question_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_company_faqs_uuid'), 'company_faqs', ['uuid'], unique=True, schema='knowledge')
    op.create_table('knowledge_base_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('covered_topics', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('source_chunk_count', sa.Integer(), nullable=False),
    sa.Column('used_for', sa.String(length=15), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['core.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_knowledge_knowledge_base_summaries_company_id'), 'knowledge_base_summaries', ['company_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_knowledge_base_summaries_created_by_id'), 'knowledge_base_summaries', ['created_by_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_knowledge_base_summaries_id'), 'knowledge_base_summaries', ['id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_knowledge_base_summaries_uuid'), 'knowledge_base_summaries', ['uuid'], unique=True, schema='knowledge')
    op.create_table('upload_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('used_for', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['core.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_knowledge_upload_methods_company_id'), 'upload_methods', ['company_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_upload_methods_filename'), 'upload_methods', ['filename'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_upload_methods_id'), 'upload_methods', ['id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_upload_methods_uploaded_by_id'), 'upload_methods', ['uploaded_by_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_upload_methods_uuid'), 'upload_methods', ['uuid'], unique=True, schema='knowledge')
    op.create_table('chatbot_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('visitor_email', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lead_created', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['knowledge.chat_bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_knowledge_chatbot_conversations_chatbot_id'), 'chatbot_conversations', ['chatbot_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_chatbot_conversations_id'), 'chatbot_conversations', ['id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_chatbot_conversations_uuid'), 'chatbot_conversations', ['uuid'], unique=True, schema='knowledge')
    op.create_table('chatbot_lead_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['knowledge.chat_bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_knowledge_chatbot_lead_fields_chatbot_id'), 'chatbot_lead_fields', ['chatbot_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_chatbot_lead_fields_id'), 'chatbot_lead_fields', ['id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_chatbot_lead_fields_uuid'), 'chatbot_lead_fields', ['uuid'], unique=True, schema='knowledge')
    op.create_table('extracted_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('upload_method_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_content', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_method_id'], ['knowledge.upload_methods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_method_id', 'chunk_index', name='uix_method_chunk'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_knowledge_extracted_data_company_id'), 'extracted_data', ['company_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_extracted_data_id'), 'extracted_data', ['id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_extracted_data_upload_method_id'), 'extracted_data', ['upload_method_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_extracted_data_uuid'), 'extracted_data', ['uuid'], unique=True, schema='knowledge')
    op.create_table('knowledge_base_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['summary_id'], ['knowledge.knowledge_base_summaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_knowledge_knowledge_base_gaps_company_id'), 'knowledge_base_gaps', ['company_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_knowledge_base_gaps_id'), 'knowledge_base_gaps', ['id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_knowledge_base_gaps_summary_id'), 'knowledge_base_gaps', ['summary_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_knowledge_base_gaps_uuid'), 'knowledge_base_gaps', ['uuid'], unique=True, schema='knowledge')
    op.create_table('knowledge_base_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('survey_category', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('generated_from', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"website": false, "documents": false, "knowledge_base": true}\'::jsonb'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('previous_version_id', sa.UUID(), nullable=True),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='available', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['summary_id'], ['knowledge.knowledge_base_summaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_knowledge_knowledge_base_surveys_company_id'), 'knowledge_base_surveys', ['company_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_knowledge_base_surveys_created_by_id'), 'knowledge_base_surveys', ['created_by_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_knowledge_base_surveys_id'), 'knowledge_base_surveys', ['id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_knowledge_base_surveys_previous_version_id'), 'knowledge_base_surveys', ['previous_version_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_knowledge_base_surveys_summary_id'), 'knowledge_base_surveys', ['summary_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_knowledge_base_surveys_survey_category'), 'knowledge_base_surveys', ['survey_category'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_knowledge_base_surveys_uuid'), 'knowledge_base_surveys', ['uuid'], unique=True, schema='knowledge')
    op.create_table('chatbot_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['knowledge.chat_bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['knowledge.chatbot_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_knowledge_chatbot_leads_chatbot_id'), 'chatbot_leads', ['chatbot_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_chatbot_leads_conversation_id'), 'chatbot_leads', ['conversation_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_chatbot_leads_id'), 'chatbot_leads', ['id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_chatbot_leads_uuid'), 'chatbot_leads', ['uuid'], unique=True, schema='knowledge')
    op.create_table('chatbot_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['knowledge.chatbot_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_knowledge_chatbot_messages_conversation_id'), 'chatbot_messages', ['conversation_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_chatbot_messages_id'), 'chatbot_messages', ['id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_chatbot_messages_uuid'), 'chatbot_messages', ['uuid'], unique=True, schema='knowledge')
    op.create_table('knowledge_base_survey_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('submission_channel', sa.String(length=32), server_default='web_form', nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['survey_id'], ['knowledge.knowledge_base_surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_knowledge_knowledge_base_survey_responses_company_id'), 'knowledge_base_survey_responses', ['company_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_knowledge_base_survey_responses_created_by_id'), 'knowledge_base_survey_responses', ['created_by_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_knowledge_base_survey_responses_id'), 'knowledge_base_survey_responses', ['id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_knowledge_base_survey_responses_survey_id'), 'knowledge_base_survey_responses', ['survey_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_knowledge_base_survey_responses_uuid'), 'knowledge_base_survey_responses', ['uuid'], unique=True, schema='knowledge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_knowledge_base_survey_responses_uuid'), table_name='knowledge_base_survey_responses', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_survey_responses_survey_id'), table_name='knowledge_base_survey_responses', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_survey_responses_id'), table_name='knowledge_base_survey_responses', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_survey_responses_created_by_id'), table_name='knowledge_base_survey_responses', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_survey_responses_company_id'), table_name='knowledge_base_survey_responses', schema='knowledge')
    op.drop_table('knowledge_base_survey_responses', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chatbot_messages_uuid'), table_name='chatbot_messages', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chatbot_messages_id'), table_name='chatbot_messages', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chatbot_messages_conversation_id'), table_name='chatbot_messages', schema='knowledge')
    op.drop_table('chatbot_messages', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chatbot_leads_uuid'), table_name='chatbot_leads', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chatbot_leads_id'), table_name='chatbot_leads', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chatbot_leads_conversation_id'), table_name='chatbot_leads', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chatbot_leads_chatbot_id'), table_name='chatbot_leads', schema='knowledge')
    op.drop_table('chatbot_leads', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_surveys_uuid'), table_name='knowledge_base_surveys', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_surveys_survey_category'), table_name='knowledge_base_surveys', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_surveys_summary_id'), table_name='knowledge_base_surveys', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_surveys_previous_version_id'), table_name='knowledge_base_surveys', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_surveys_id'), table_name='knowledge_base_surveys', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_surveys_created_by_id'), table_name='knowledge_base_surveys', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_surveys_company_id'), table_name='knowledge_base_surveys', schema='knowledge')
    op.drop_table('knowledge_base_surveys', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_gaps_uuid'), table_name='knowledge_base_gaps', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_gaps_summary_id'), table_name='knowledge_base_gaps', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_gaps_id'), table_name='knowledge_base_gaps', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_gaps_company_id'), table_name='knowledge_base_gaps', schema='knowledge')
    op.drop_table('knowledge_base_gaps', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_extracted_data_uuid'), table_name='extracted_data', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_extracted_data_upload_method_id'), table_name='extracted_data', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_extracted_data_id'), table_name='extracted_data', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_extracted_data_company_id'), table_name='extracted_data', schema='knowledge')
    op.drop_table('extracted_data', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chatbot_lead_fields_uuid'), table_name='chatbot_lead_fields', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chatbot_lead_fields_id'), table_name='chatbot_lead_fields', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chatbot_lead_fields_chatbot_id'), table_name='chatbot_lead_fields', schema='knowledge')
    op.drop_table('chatbot_lead_fields', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chatbot_conversations_uuid'), table_name='chatbot_conversations', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chatbot_conversations_id'), table_name='chatbot_conversations', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chatbot_conversations_chatbot_id'), table_name='chatbot_conversations', schema='knowledge')
    op.drop_table('chatbot_conversations', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_upload_methods_uuid'), table_name='upload_methods', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_upload_methods_uploaded_by_id'), table_name='upload_methods', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_upload_methods_id'), table_name='upload_methods', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_upload_methods_filename'), table_name='upload_methods', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_upload_methods_company_id'), table_name='upload_methods', schema='knowledge')
    op.drop_table('upload_methods', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_summaries_uuid'), table_name='knowledge_base_summaries', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_summaries_id'), table_name='knowledge_base_summaries', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_summaries_created_by_id'), table_name='knowledge_base_summaries', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_base_summaries_company_id'), table_name='knowledge_base_summaries', schema='knowledge')
    op.drop_table('knowledge_base_summaries', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_company_faqs_uuid'), table_name='company_faqs', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_company_faqs_question_id'), table_name='company_faqs', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_company_faqs_id'), table_name='company_faqs', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_company_faqs_company_id'), table_name='company_faqs', schema='knowledge')
    op.drop_table('company_faqs', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chat_bots_uuid'), table_name='chat_bots', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chat_bots_id'), table_name='chat_bots', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chat_bots_created_by_id'), table_name='chat_bots', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_chat_bots_company_id'), table_name='chat_bots', schema='knowledge')
    op.drop_table('chat_bots', schema='knowledge')
    op.execute('DROP SCHEMA IF EXISTS "knowledge" CASCADE')
    # ### end Alembic commands ###
